package nodomain.freeyourgadget.gadgetbridge.entities;
import android.os.Build;
import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import nodomain.freeyourgadget.gadgetbridge.entities.WithingsSteelHRActivitySample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WITHINGS_STEEL_HRACTIVITY_SAMPLE".
*/
public class WithingsSteelHRActivitySampleDao extends AbstractDao<WithingsSteelHRActivitySample, Void> {

    public static final String TABLENAME = "WITHINGS_STEEL_HRACTIVITY_SAMPLE";

    /**
     * Properties of entity WithingsSteelHRActivitySample.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Timestamp = new Property(0, int.class, "timestamp", true, "TIMESTAMP");
        public final static Property DeviceId = new Property(1, long.class, "deviceId", true, "DEVICE_ID");
        public final static Property UserId = new Property(2, long.class, "userId", false, "USER_ID");
        public final static Property Duration = new Property(3, int.class, "duration", false, "DURATION");
        public final static Property RawKind = new Property(4, int.class, "rawKind", false, "RAW_KIND");
        public final static Property Steps = new Property(5, int.class, "steps", false, "STEPS");
        public final static Property Distance = new Property(6, int.class, "distance", false, "DISTANCE");
        public final static Property Calories = new Property(7, int.class, "calories", false, "CALORIES");
        public final static Property HeartRate = new Property(8, int.class, "heartRate", false, "HEART_RATE");
        public final static Property RawIntensity = new Property(9, int.class, "rawIntensity", false, "RAW_INTENSITY");
    };

    private DaoSession daoSession;


    public WithingsSteelHRActivitySampleDao(DaoConfig config) {
        super(config);
    }
    
    public WithingsSteelHRActivitySampleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WITHINGS_STEEL_HRACTIVITY_SAMPLE\" (" + //
                "\"TIMESTAMP\" INTEGER  NOT NULL ," + // 0: timestamp
                "\"DEVICE_ID\" INTEGER  NOT NULL ," + // 1: deviceId
                "\"USER_ID\" INTEGER NOT NULL ," + // 2: userId
                "\"DURATION\" INTEGER NOT NULL ," + // 3: duration
                "\"RAW_KIND\" INTEGER NOT NULL ," + // 4: rawKind
                "\"STEPS\" INTEGER NOT NULL ," + // 5: steps
                "\"DISTANCE\" INTEGER NOT NULL ," + // 6: distance
                "\"CALORIES\" INTEGER NOT NULL ," + // 7: calories
                "\"HEART_RATE\" INTEGER NOT NULL ," + // 8: heartRate
                "\"RAW_INTENSITY\" INTEGER NOT NULL ," + // 9: rawIntensity
                "PRIMARY KEY (" +
                "\"TIMESTAMP\" ," +
                "\"DEVICE_ID\" ) ON CONFLICT REPLACE)" + ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) ? " WITHOUT ROWID;" : ";")
        );
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WITHINGS_STEEL_HRACTIVITY_SAMPLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WithingsSteelHRActivitySample entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimestamp());
        stmt.bindLong(2, entity.getDeviceId());
        stmt.bindLong(3, entity.getUserId());
        stmt.bindLong(4, entity.getDuration());
        stmt.bindLong(5, entity.getRawKind());
        stmt.bindLong(6, entity.getSteps());
        stmt.bindLong(7, entity.getDistance());
        stmt.bindLong(8, entity.getCalories());
        stmt.bindLong(9, entity.getHeartRate());
        stmt.bindLong(10, entity.getRawIntensity());
    }

    @Override
    protected void attachEntity(WithingsSteelHRActivitySample entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public WithingsSteelHRActivitySample readEntity(Cursor cursor, int offset) {
        WithingsSteelHRActivitySample entity = new WithingsSteelHRActivitySample( //
            cursor.getInt(offset + 0), // timestamp
            cursor.getLong(offset + 1), // deviceId
            cursor.getLong(offset + 2), // userId
            cursor.getInt(offset + 3), // duration
            cursor.getInt(offset + 4), // rawKind
            cursor.getInt(offset + 5), // steps
            cursor.getInt(offset + 6), // distance
            cursor.getInt(offset + 7), // calories
            cursor.getInt(offset + 8), // heartRate
            cursor.getInt(offset + 9) // rawIntensity
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WithingsSteelHRActivitySample entity, int offset) {
        entity.setTimestamp(cursor.getInt(offset + 0));
        entity.setDeviceId(cursor.getLong(offset + 1));
        entity.setUserId(cursor.getLong(offset + 2));
        entity.setDuration(cursor.getInt(offset + 3));
        entity.setRawKind(cursor.getInt(offset + 4));
        entity.setSteps(cursor.getInt(offset + 5));
        entity.setDistance(cursor.getInt(offset + 6));
        entity.setCalories(cursor.getInt(offset + 7));
        entity.setHeartRate(cursor.getInt(offset + 8));
        entity.setRawIntensity(cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(WithingsSteelHRActivitySample entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(WithingsSteelHRActivitySample entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDeviceDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM WITHINGS_STEEL_HRACTIVITY_SAMPLE T");
            builder.append(" LEFT JOIN DEVICE T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN USER T1 ON T.\"USER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected WithingsSteelHRActivitySample loadCurrentDeep(Cursor cursor, boolean lock) {
        WithingsSteelHRActivitySample entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Device device = loadCurrentOther(daoSession.getDeviceDao(), cursor, offset);
         if(device != null) {
            entity.setDevice(device);
        }
        offset += daoSession.getDeviceDao().getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }

        return entity;    
    }

    public WithingsSteelHRActivitySample loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<WithingsSteelHRActivitySample> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<WithingsSteelHRActivitySample> list = new ArrayList<WithingsSteelHRActivitySample>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<WithingsSteelHRActivitySample> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<WithingsSteelHRActivitySample> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
