package nodomain.freeyourgadget.gadgetbridge.entities;
import android.os.Build;
import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import nodomain.freeyourgadget.gadgetbridge.entities.XiaomiSleepTimeSample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "XIAOMI_SLEEP_TIME_SAMPLE".
*/
public class XiaomiSleepTimeSampleDao extends AbstractDao<XiaomiSleepTimeSample, Void> {

    public static final String TABLENAME = "XIAOMI_SLEEP_TIME_SAMPLE";

    /**
     * Properties of entity XiaomiSleepTimeSample.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Timestamp = new Property(0, long.class, "timestamp", true, "TIMESTAMP");
        public final static Property DeviceId = new Property(1, long.class, "deviceId", true, "DEVICE_ID");
        public final static Property UserId = new Property(2, long.class, "userId", false, "USER_ID");
        public final static Property WakeupTime = new Property(3, Long.class, "wakeupTime", false, "WAKEUP_TIME");
        public final static Property IsAwake = new Property(4, Boolean.class, "isAwake", false, "IS_AWAKE");
        public final static Property TotalDuration = new Property(5, Integer.class, "totalDuration", false, "TOTAL_DURATION");
        public final static Property DeepSleepDuration = new Property(6, Integer.class, "deepSleepDuration", false, "DEEP_SLEEP_DURATION");
        public final static Property LightSleepDuration = new Property(7, Integer.class, "lightSleepDuration", false, "LIGHT_SLEEP_DURATION");
        public final static Property RemSleepDuration = new Property(8, Integer.class, "remSleepDuration", false, "REM_SLEEP_DURATION");
        public final static Property AwakeDuration = new Property(9, Integer.class, "awakeDuration", false, "AWAKE_DURATION");
    };

    private DaoSession daoSession;


    public XiaomiSleepTimeSampleDao(DaoConfig config) {
        super(config);
    }
    
    public XiaomiSleepTimeSampleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"XIAOMI_SLEEP_TIME_SAMPLE\" (" + //
                "\"TIMESTAMP\" INTEGER  NOT NULL ," + // 0: timestamp
                "\"DEVICE_ID\" INTEGER  NOT NULL ," + // 1: deviceId
                "\"USER_ID\" INTEGER NOT NULL ," + // 2: userId
                "\"WAKEUP_TIME\" INTEGER," + // 3: wakeupTime
                "\"IS_AWAKE\" INTEGER," + // 4: isAwake
                "\"TOTAL_DURATION\" INTEGER," + // 5: totalDuration
                "\"DEEP_SLEEP_DURATION\" INTEGER," + // 6: deepSleepDuration
                "\"LIGHT_SLEEP_DURATION\" INTEGER," + // 7: lightSleepDuration
                "\"REM_SLEEP_DURATION\" INTEGER," + // 8: remSleepDuration
                "\"AWAKE_DURATION\" INTEGER," + // 9: awakeDuration
                "PRIMARY KEY (" +
                "\"TIMESTAMP\" ," +
                "\"DEVICE_ID\" ) ON CONFLICT REPLACE)" + ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) ? " WITHOUT ROWID;" : ";")
        );
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"XIAOMI_SLEEP_TIME_SAMPLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, XiaomiSleepTimeSample entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimestamp());
        stmt.bindLong(2, entity.getDeviceId());
        stmt.bindLong(3, entity.getUserId());
 
        Long wakeupTime = entity.getWakeupTime();
        if (wakeupTime != null) {
            stmt.bindLong(4, wakeupTime);
        }
 
        Boolean isAwake = entity.getIsAwake();
        if (isAwake != null) {
            stmt.bindLong(5, isAwake ? 1L: 0L);
        }
 
        Integer totalDuration = entity.getTotalDuration();
        if (totalDuration != null) {
            stmt.bindLong(6, totalDuration);
        }
 
        Integer deepSleepDuration = entity.getDeepSleepDuration();
        if (deepSleepDuration != null) {
            stmt.bindLong(7, deepSleepDuration);
        }
 
        Integer lightSleepDuration = entity.getLightSleepDuration();
        if (lightSleepDuration != null) {
            stmt.bindLong(8, lightSleepDuration);
        }
 
        Integer remSleepDuration = entity.getRemSleepDuration();
        if (remSleepDuration != null) {
            stmt.bindLong(9, remSleepDuration);
        }
 
        Integer awakeDuration = entity.getAwakeDuration();
        if (awakeDuration != null) {
            stmt.bindLong(10, awakeDuration);
        }
    }

    @Override
    protected void attachEntity(XiaomiSleepTimeSample entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public XiaomiSleepTimeSample readEntity(Cursor cursor, int offset) {
        XiaomiSleepTimeSample entity = new XiaomiSleepTimeSample( //
            cursor.getLong(offset + 0), // timestamp
            cursor.getLong(offset + 1), // deviceId
            cursor.getLong(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // wakeupTime
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isAwake
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // totalDuration
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // deepSleepDuration
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // lightSleepDuration
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // remSleepDuration
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9) // awakeDuration
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, XiaomiSleepTimeSample entity, int offset) {
        entity.setTimestamp(cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.getLong(offset + 1));
        entity.setUserId(cursor.getLong(offset + 2));
        entity.setWakeupTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsAwake(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setTotalDuration(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDeepSleepDuration(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setLightSleepDuration(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setRemSleepDuration(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setAwakeDuration(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(XiaomiSleepTimeSample entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(XiaomiSleepTimeSample entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDeviceDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM XIAOMI_SLEEP_TIME_SAMPLE T");
            builder.append(" LEFT JOIN DEVICE T0 ON T.\"DEVICE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN USER T1 ON T.\"USER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected XiaomiSleepTimeSample loadCurrentDeep(Cursor cursor, boolean lock) {
        XiaomiSleepTimeSample entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Device device = loadCurrentOther(daoSession.getDeviceDao(), cursor, offset);
         if(device != null) {
            entity.setDevice(device);
        }
        offset += daoSession.getDeviceDao().getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }

        return entity;    
    }

    public XiaomiSleepTimeSample loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<XiaomiSleepTimeSample> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<XiaomiSleepTimeSample> list = new ArrayList<XiaomiSleepTimeSample>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<XiaomiSleepTimeSample> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<XiaomiSleepTimeSample> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
